In [1]:
import gdown

In [ ]:
https://docs.google.com/spreadsheets/d/1tq8l92xs3AQFGbUayahhDZJmcQfrriiX2HSuQyK85uc/edit?usp=sharing
https://docs.google.com/spreadsheets/d/e/2PACX-1vQKyi_h8BjQn_oLs0z0Zz8KxDhqY2iOr6n96TlXHod4ROr15WMWiPpwIRIQx5Q92jR4QSjPa7M8NEZI/pub?output=csv
https://drive.google.com/open?id=1tq8l92xs3AQFGbUayahhDZJmcQfrriiX2HSuQyK85uc

In [10]:
gdown.download(
    "https://drive.google.com/uc?id=1tq8l92xs3AQFGbUayahhDZJmcQfrriiX2HSuQyK85uc",
    "lala.csv",
)

Permission denied: https://drive.google.com/uc?id=1tq8l92xs3AQFGbUayahhDZJmcQfrriiX2HSuQyK85uc
Maybe you need to change permission over 'Anyone with the link'?

In [5]:
import pandas as pd

In [13]:
pd.read_csv("lala.csv")

,id,value,feed_id,created_at,lat,lon,ele
0,0DXPXB5QEVSF9QGHV6TC35S2Q7,26,828771,2018-07-13 08:04:29 UTC,NaN,NaN,NaN
1,0DXPXBFWS0NP9ZY1FE0GWS8CTF,26,828771,2018-07-13 08:05:02 UTC,NaN,NaN,NaN
2,0DXPXBT1PXX3RSXZHK55952X7M,26,828771,2018-07-13 08:05:36 UTC,NaN,NaN,NaN
3,0DXPXC46TGS5D14SJB6JJJ70E6,26,828771,2018-07-13 08:06:09 UTC,NaN,NaN,NaN
4,0DXPXCEBTPDT2RV61TS4JFAHFX,26,828771,2018-07-13 08:06:42 UTC,NaN,NaN,NaN
...,...,...,...,...,...,...,...
61200,0DY9XW86WCWWTS2EFQA4YEJZNP,35,828771,2018-08-05 23:16:09 UTC,NaN,NaN,NaN
61201,0DY9XWJD5Z5JK6X9M8X756CS4Q,34,828771,2018-08-05 23:16:43 UTC,NaN,NaN,NaN
61202,0DY9XWWH49D6H1X0XC5HCD4W2F,35,828771,2018-08-05 23:17:16 UTC,NaN,NaN,NaN
61203,0DY9XX6PW5GW3GJ8Q2RJBPK49E,34,828771,2018-08-05 23:17:49 UTC,NaN,NaN,NaN
61204,0DY9XXH4Z4K8GZDBEG0NXSE1T2,70,828771,2018-08-05 23:18:23 UTC,NaN,NaN,NaN